POST http://localhost:3003/api/blog
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkRhdmlkIiwiaWQiOiI2NDZlNGM5ZjRiODE2OGM2NDhkMzc5ZWYiLCJpYXQiOjE2ODUwNDIwMDN9.w5NZT-7RCvGJCUBlHVGn28YeKqoB7AZWzycPEQbrwOo

{
"title": "MIDDELWARE USER EXTRACTION 1001",
"author": "Michael Chan",
"url": "https://reactpatterns.com/",
"likes": 17,
"id": "646e4ca4be8d8cdc58a9bb16"
}

###

POST http://localhost:3003/api/login
Content-Type: application/json

{
    "username": "David",
    "passwordHash": "987456123"
}

###

DELETE http://localhost:3003/api/blog/646fb6dd4e7c0dc7b2e02aa9
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkRhdmlkIiwiaWQiOiI2NDZlNGM5ZjRiODE2OGM2NDhkMzc5ZWYiLCJpYXQiOjE2ODUwMjgxODl9.MBfeRIZDj2-DhzQHFZq9I9_nHZh514cP8oZSqX5Q_Ig